on:
  workflow_dispatch:
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create a GitHub issue using GITHUB_TOKEN
        run: gh issue create --title "Bug Report" --body "Something went wrong!" --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
