on:
  workflow_dispatch:
jobs:
  test_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          echo "Running tests..."
          echo "| Test Name | Status |" >> results.md
          echo "|-----------|--------|" >> results.md
          echo "| Login Test | ✅ Pass |" >> results.md
          echo "| Signup Test | ❌ Fail |" >> results.md
          cat results.md >> $GITHUB_STEP_SUMMARY
