on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Set API Key
      run: echo "::add-mask::12345" >> $GITHUB_ENV

    - name: Use API Key
      run: echo "Using API Key ::add-mask::$API_KEY"
