on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Set API Key
        run: |
          echo "::add-mask::12345"  # Masking the value
          echo "API_KEY=12345" >> $GITHUB_ENV  # Setting environment variable

      - name: Use API Key
        run: echo "Using API Key $API_KEY"
